# Generated by Django 6.1 on 2026-08-18 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=200, unique=True)),
                ('ip', models.CharField(max_length=200)),
                ('setor', models.CharField(max_length=200)),
                ('ultima_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_remaining', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('NAO_MONITORADA', 'Não monitorada')], default='OK', max_length=20)),
            ],
            options={
                'ordering': ['setor'],
            },
        ),
    ]
