# Generated by Django 6.1 on 2026-09-29 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='data_remaining',
        ),
        migrations.AddField(
            model_name='printer',
            name='nivel_toner',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
