# Generated by Django 6.1 on 2026-09-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer_monitor', '0002_remove_printer_data_remaining_printer_nivel_toner'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='toner_recem_trocado',
            field=models.BooleanField(default=False),
        ),
    ]
